name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        repository: roslynpad/roslynpad
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
    - name: Build with dotnet
      run: dotnet build /flp:v=diag -c Release -m:1 src/RoslynPad.sln
# This can be used to debug if the path changed somehow
#    - uses: actions/upload-artifact@v4
#      if: always()
#      with:
#        name: root
#        path: |
#          ./
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: build-log
        path: |
          msbuild.log
    - uses: actions/upload-artifact@v4
      with:
        name: roslynpad
        path: |
          src/RoslynPad/bin/Release/net8.0-windows/win-x64
